
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqcdsvsiqgtyidmqvosh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY2RzdnNpcWd0eWlkbXF2b3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MDg4NTMsImV4cCI6MjA1ODI4NDg1M30.AN83ePQUy7ae1DXnERBLUkJPqaOTpd1LwwaOAwrj-Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
